apiVersion: v1
data:
    admin-password: {{ (index .OpenCenter.ManagedServices "kube-prometheus-proxy").AdminPassword }} 
    admin-user: {{ (index .OpenCenter.ManagedServices "kube-prometheus-proxy").AdminUser }} 
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: observability
