logging:
    level: warn
    format: text
    output: stderr
    file:
        maxSize: 100
        maxBackups: 3
        maxAge: 28
        compress: true
paths:
    configDir: /Users/victor.palma/projects/rackspace/openCenter-cli/tmp/test-full
    clustersDir: /Users/victor.palma/projects/rackspace/openCenter-cli/tmp/test-full/clusters
    pluginsDir: /Users/victor.palma/projects/rackspace/openCenter-cli/tmp/test-full/plugins
behavior:
    autoConfirm: false
    dryRun: false
    verbose: false
defaults:
    provider: openstack
    region: '{{ .OpenCenter.Cluster.ClusterRegion }}'
    environment: dev
