---
cluster:
    name: 
cloudConfig:
    global:
        auth-url: 
        application-credential-id: 
        application-credential-secret: 
        domain-name: 
        region: 
        tenant-name: 
        tls-insecure: 
    loadBalancer:
        floating-network-id: 
        subnet-id: 
