---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vmware-system-csi
resources:
  - "./storageclass-retain.yaml"
  - "./vsphere-config-secret.yaml"
  - "./vsphere-cpi-secret.yaml"
secretGenerator:
  - name: vsphere-csi-values-override
    type: Opaque
    files: [override.yaml=helm-values/override-values.yaml]
    options:
      disableNameSuffixHash: true