apiVersion: v1
kind: Secret
metadata:
    name: vsphere-config-secret
    namespace: vmware-system-csi
type: Opaque
stringData:
    csi-vsphere.conf: |
        [Global]
        cluster-id = "{{ .ClusterName }}"

        [VirtualCenter "{{ .OpenCenter.Secrets.VSphereCsi.VCenterHost }}"]
        insecure-flag = "{{ .OpenCenter.Secrets.VSphereCsi.InsecureFlag }}"
        user = "{{ .OpenCenter.Secrets.VSphereCsi.Username }}"
        password = "{{ .OpenCenter.Secrets.VSphereCsi.Password }}"
        port = "{{ .OpenCenter.Secrets.VSphereCsi.Port }}"
        datacenters = "{{ .OpenCenter.Secrets.VSphereCsi.Datacenters }}"