apiVersion: v1
data:
    csi-vsphere.conf: {{ .OpenCenter.Secrets.Vsphere-csi.config | base64}}
kind: Secret
metadata:
    creationTimestamp: null
    name: vsphere-csi
    namespace: vmware-system-csi