apiVersion: v1
kind: Secret
metadata:
    name: vsphere-cpi-secret
    namespace: vmware-system-csi
type: Opaque
stringData:
    # vSphere configuration for CPI
    vsphere.conf: "# Global properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.\nglobal:\n  port: 443\n  # set insecureFlag to true if the vCenter uses a self-signed cert\n  insecureFlag: true\n  # settings for using k8s secret\n  secretName: vsphere-cloud-secret\n  secretNamespace: kube-system\n\n# vcenter section\nvcenter:\n  iad3-1369839:\n    server: svc01m.iad3-1369839.sddc.rackspace-cloud.com\n    user: opencenter@vsphere.local\n    password: \"x79kDrIIKf6#\" \n    datacenters:\n      - IAD3-1643323-01\n"
